Setbacks refactor
NREL/reVX pull request #159
Opened 2022-08-21 23:39 UTC by ppinchuk

Major code refactor to allow either solar or wind regulations inputs to all setback types, including future setback implementations.

2022-08-25 17:00 UTC, grantbuster requested changes

2022-08-25 17:00 UTC, grantbuster commented on reVX/setbacks/structure_setbacks.py
> +class StructureSetbacks(BaseSetbacks):
nice, these look like really clean + simple concrete subclasses. A sign of a good refactor!

2022-08-25 20:10 UTC, ppinchuk commented on reVX/setbacks/base.py
> +class _Rasterizer:
Yea, that's a good point actually. This is why it's good to have a second set of eyes, thank you! :)

2022-08-25 20:23 UTC, ppinchuk commented on reVX/setbacks/base.py
> +            example, setting the value to `3` would split each output
Yea... it's tricky b/c it has to work this way, unless we put in a flag and then have a required value if the flag is true, which is slightly messier IMO (though let me know if you disagree and I can change it). I did try to compensate for the non-straightforward nature of this value with a through docstring, which I updated based on this comment. Let me know if you think it's still too confusing.

2022-08-25 20:30 UTC, ppinchuk commented on reVX/setbacks/base.py
>  class BaseSetbacks:
Yea good call... This class actually used to be abstract but went through so many iterations that it got lost in translation. In the current state there is at least 1 function that I would call abstract so I do think it makes sense to make it an ABC. Added this change, thank you!

2022-08-29 15:18 UTC, ppinchuk commented on reVX/setbacks/base.py
> +            example, setting the value to `3` would split each output
Yes, that is a reV limitation. There is no option for "exclusion weights", so if anyone wanted to model partial setbacks, they have to input inclusion weights to reV: https://github.com/NREL/reV/blob/13525b8802e526dca09cd8ee66784a9f3e01eb60/reV/supply_curve/exclusions.py#L23-L35

2022-08-29 15:31 UTC, grantbuster commented on reVX/setbacks/base.py
> +            example, setting the value to `3` would split each output
Ah i see, okay thats annoying on the reV side but makes sense. No need to fix for now.

2022-08-29 15:31 UTC, grantbuster approved these changes

2022-08-29 15:33 UTC, merged